version: 2.1

orbs:
  architect: giantswarm/architect@4.0.0

workflows:
  test:
    jobs:
      - architect/go-test:
          name: go-test
          filters:
            # Trigger job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: "architect"
          name: push-apptest-app-to-control-plane-test-catalog
          app_catalog: "control-plane-test-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "apptest-app"
          filters:
            # Do not trigger the job on merge to master.
            branches:
              ignore:
                - master
          requires:
            - go-test

      - architect/integration-test:
          name: "basic-integration-test"
          install-app-platform: true
          test-dir: "integration/test/basic"
          filters:
            # Do not trigger the job on merge to master.
            branches:
              ignore:
                - master
          requires:
            - push-apptest-app-to-control-plane-test-catalog

      - architect/integration-test:
          name: "ensure-crds-integration-test"
          install-app-platform: true
          test-dir: "integration/test/ensurecrds"
          filters:
            # Do not trigger the job on merge to master.
            branches:
              ignore:
                - master
          requires:
            - push-apptest-app-to-control-plane-test-catalog

      - architect/integration-test:
          name: "external-catalog-integration-test"
          install-app-platform: true
          test-dir: "integration/test/externalcatalog"
          filters:
            # Do not trigger the job on merge to master.
            branches:
              ignore:
                - master
          requires:
            - push-apptest-app-to-control-plane-test-catalog
